### ISSUE TITLE
Support nested syntax

### ISSUE THREAD

**Issue by Nixinova** [NovaSheets/vscode#1]
This extension currently does not support CSS nesting, to be added in 1.0.0.

Example:
<table><tr><th>CSS</th><th>NVSS 0.x</th><th>NVSS 1.0</th></tr>
<tr>
<td>

```css
footer {color: black;}
footer a {font-size: 90%;}
```

</td><td>

```less
footer {color: black;}
 & a {font-size: 90%;}
```

</td><td>

```less
footer {
  color: black;
  a {font-size: 90%;}
}
```

</td></tr></table>

Need to fix newlines breaking selector highlighting to allow for this.
